### ISSUE TITLE
Update to 12.3 broke compatibility with space exploration

### ISSUE THREAD

**Issue by evilphish** [jpanther/dectorio#207]
After updating from 12.2 to 12.3 starting the game yields the following error:

`76.620 Error Util.cpp:83: Error in assignID: item with name 'space-science-pack' does not exist. It was removed by space-exploration-postprocess.`

If I can help in any way please let me know.

**Comment by jpanther** [comment]
Thanks for the report, I'll get a patch out shortly to fix this.

**Comment by shadbags** [comment]
I just posted #208 that has a new error in migration, also in an SE map.
